els-ASAP auto commit file/tag grep-2.20-3.el6.src.rpm

diff --git a/src/tests/Makefile.am b/src/tests/Makefile.am
--- a/src/tests/Makefile.am
+++ b/src/tests/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to create Makefile.in
-# Copyright 1997-1998, 2005-2010 Free Software Foundation, Inc.
+# Copyright 1997-1998, 2005-2014 Free Software Foundation, Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,41 +22,95 @@ AM_CFLAGS = $(WARN_CFLAGS) $(WERROR_CFLAGS)
 AM_LDFLAGS = $(IGNORE_UNUSED_LIBRARIES_CFLAGS)
 LDADD = ../lib/libgreputils.a $(LIBINTL) ../lib/libgreputils.a
 
+XFAIL_TESTS =
+
+# Equivalence classes are only supported when using the system
+# matcher (which means only with glibc).
+if USE_INCLUDED_REGEX
+XFAIL_TESTS += equiv-classes
+endif
+
 TESTS =						\
-  backref.sh					\
+  backref					\
+  backref-multibyte-slow			\
   backref-word					\
-  bre.sh					\
+  backslash-s-and-repetition-operators		\
+  backslash-s-vs-invalid-multitype		\
+  big-hole					\
+  big-match					\
+  bogus-wctob					\
+  bre						\
   case-fold-backref				\
   case-fold-backslash-w				\
   case-fold-char-class				\
   case-fold-char-range				\
   case-fold-char-type				\
+  case-fold-titlecase				\
   char-class-multibyte				\
+  char-class-multibyte2				\
+  context-0					\
+  count-newline					\
+  dfa-coverage					\
+  dfa-heap-overrun				\
   dfaexec-multibyte				\
   empty						\
-  ere.sh					\
+  empty-line					\
+  epipe						\
+  equiv-classes					\
+  ere						\
   euc-mb					\
   fedora					\
   fgrep-infloop					\
-  file.sh					\
+  file						\
   fmbtest					\
   foad1						\
+  grep-dev-null					\
+  grep-dir					\
   help-version					\
+  in-eq-out-infloop				\
   include-exclude				\
-  khadafy.sh					\
+  inconsistent-range				\
+  invalid-multibyte-infloop			\
+  khadafy					\
+  long-line-vs-2GiB-read			\
+  max-count-overread				\
   max-count-vs-context				\
-  options.sh					\
-  pcre.sh					\
+  mb-non-UTF8-performance			\
+  multibyte-white-space				\
+  multiple-begin-or-end-line			\
+  null-byte					\
+  empty-line-mb					\
+  unibyte-bracket-expr				\
+  unibyte-negated-circumflex			\
+  high-bit-range				\
+  options					\
+  pcre						\
+  pcre-abort					\
+  pcre-infloop					\
+  pcre-invalid-utf8-input			\
+  pcre-utf8					\
+  pcre-w					\
+  pcre-wx-backref				\
   pcre-z					\
-  reversed-range-endpoints			\
-  sjis-mb					\
-  spencer1.sh					\
-  spencer1-locale				\
-  status.sh					\
+  posix-bracket					\
   prefix-of-multibyte				\
-  warning.sh					\
+  r-dot						\
+  repetition-overflow				\
+  reversed-range-endpoints			\
+  skip-device					\
+  sjis-mb					\
+  spencer1					\
+  spencer1-locale				\
+  status					\
+  surrogate-pair				\
+  symlink					\
+  turkish-eyes					\
+  turkish-I					\
+  turkish-I-without-dot				\
+  warn-char-classes				\
+  word-delim-multibyte				\
   word-multi-file				\
-  yesno.sh
+  yesno
 
 EXTRA_DIST =					\
   $(TESTS)					\
@@ -72,36 +126,35 @@ EXTRA_DIST =					\
   spencer1.tests				\
   spencer1-locale.awk
 
-CLEANFILES = \
-  spencer1.script bre.script ere.script khadafy.out patfile \
-  cspatfile csinput yesno.txt 112869.out 116909.in 116909.list \
-  116909.out 123362.out 161700.out 171379.out 179698.out \
-  204255.first 204255.second
+# Default to a nonzero value.  Environment overrides.
+# http://udrepper.livejournal.com/11429.html
+MALLOC_PERTURB_ = 1
 
 TESTS_ENVIRONMENT =				\
   tmp__=$$TMPDIR; test -d "$$tmp__" || tmp__=.;	\
   TMPDIR=$$tmp__; export TMPDIR;		\
-  exec 9>&2;					\
-  shell_or_perl_() {				\
-    if grep '^\#!/usr/bin/perl' "$$1" > /dev/null; then			\
-      if $(PERL) -e 'use warnings' > /dev/null 2>&1; then		\
-	grep '^\#!/usr/bin/perl -T' "$$1" > /dev/null && T_=T || T_=;	\
-        $(PERL) -w$$T_ -I$(srcdir) -MCoreutils				\
-	      -M"CuTmpdir qw($$f)" -- "$$1";	\
-      else					\
-	echo 1>&2 "$$tst: configure did not find a usable version of Perl," \
-	  "so skipping this test";		\
-	(exit 77);				\
-      fi;					\
-    else					\
-      $(SHELL) "$$1";				\
-    fi;						\
-  };						\
-  export					\
-  LOCALE_FR='$(LOCALE_FR)'                      \
-  LOCALE_FR_UTF8='$(LOCALE_FR_UTF8)'            \
+						\
+  if test -n "$$BASH_VERSION" || (eval "export v=x") 2>/dev/null; then \
+    export_with_values () { export "$$@"; };		\
+  else							\
+    export_with_values ()				\
+    {							\
+      sed_extract_var='s/=.*//';			\
+      sed_quote_value="s/'/'\\\\''/g;s/=\\(.*\\)/='\\1'/";\
+      for arg in "$$@"; do				\
+        var=`echo "$$arg" | sed "$$sed_extract_var"`;	\
+        arg=`echo "$$arg" | sed "$$sed_quote_value"`;	\
+        eval "$$arg";					\
+        export "$$var";					\
+      done;						\
+    };							\
+  fi;							\
+						\
+  export_with_values				\
+  VERSION='$(VERSION)'				\
+  LOCALE_FR='$(LOCALE_FR)'			\
+  LOCALE_FR_UTF8='$(LOCALE_FR_UTF8)'		\
   AWK=$(AWK)					\
-  GREP=$(top_builddir)/src/grep			\
   GREP_OPTIONS=''				\
   LC_ALL=C					\
   abs_top_builddir='$(abs_top_builddir)'	\
@@ -113,11 +166,25 @@ TESTS_ENVIRONMENT =				\
   CC='$(CC)'					\
   GREP_TEST_NAME=`echo $$tst|sed 's,^\./,,;s,/,-,g'` \
   MAKE=$(MAKE)					\
+  MALLOC_PERTURB_=$(MALLOC_PERTURB_)		\
   PACKAGE_BUGREPORT='$(PACKAGE_BUGREPORT)'	\
   PACKAGE_VERSION=$(PACKAGE_VERSION)		\
   PERL='$(PERL)'				\
   SHELL='$(SHELL)'				\
   PATH='$(abs_top_builddir)/src$(PATH_SEPARATOR)'"$$PATH" \
-  ; shell_or_perl_
+  ; 9>&2
+
+LOG_COMPILER = $(SHELL)
 
 VERBOSE = yes
+
+check: check_executable_TESTS
+.PHONY: check_executable_TESTS
+check_executable_TESTS: Makefile
+	$(AM_V_GEN)fail=0;						\
+        cd $(srcdir) && for i in $(TESTS); do				\
+	  test -x $$i || { fail=1; echo $$i >&2; };			\
+	done;								\
+	test $$fail = 1							\
+          && { echo the above test scripts are not executable >&2; exit 1; } \
+          || :
diff --git a/src/tests/help-version b/src/tests/help-version
--- a/src/tests/help-version
+++ b/src/tests/help-version
@@ -2,7 +2,7 @@
 # Make sure all these programs work properly
 # when invoked with --help or --version.
 
-# Copyright (C) 2000-2010 Free Software Foundation, Inc.
+# Copyright (C) 2000-2014 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,16 +17,13 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-test "$VERBOSE" = yes && set -x
-
 # Ensure that $SHELL is set to *some* value and exported.
 # This is required for dircolors, which would fail e.g., when
 # invoked via debuild (which removes SHELL from the environment).
 test "x$SHELL" = x && SHELL=/bin/sh
 export SHELL
 
-: ${srcdir=.}
-. "$srcdir/init.sh"
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
 
 expected_failure_status_chroot=125
 expected_failure_status_env=125
@@ -59,12 +56,25 @@ expected_failure_status_egrep=2
 expected_failure_status_fgrep=2
 
 test "$built_programs" \
-  || { echo "$this_test: no programs built!?!" 1>&2; Exit 1; }
+  || fail_ "built_programs not specified!?!"
+
+test "$VERSION" \
+  || fail_ "set envvar VERSION; it is required for a PATH sanity-check"
+
+# Extract version from --version output of the first program
+for i in $built_programs; do
+  v=$(env $i --version | sed -n '1s/.* //p;q')
+  break
+done
+
+# Ensure that it matches $VERSION.
+test "x$v" = "x$VERSION" \
+  || fail_ "--version-\$VERSION mismatch"
 
 for lang in C fr da; do
   for i in $built_programs; do
 
-    # Skip `test'; it doesn't accept --help or --version.
+    # Skip 'test'; it doesn't accept --help or --version.
     test $i = test && continue;
 
     # false fails even when invoked with --help or --version.
@@ -74,7 +84,7 @@ for lang in C fr da; do
       continue
     fi
 
-    # The just-built install executable is always named `ginstall'.
+    # The just-built install executable is always named 'ginstall'.
     test $i = install && i=ginstall
 
     # Make sure they exit successfully, under normal conditions.
@@ -85,7 +95,7 @@ for lang in C fr da; do
     grep "$PACKAGE_BUGREPORT" h-$i > /dev/null || fail=1
     rm -f h-$i
 
-    # Make sure they fail upon `disk full' error.
+    # Make sure they fail upon 'disk full' error.
     if test -w /dev/full && test -c /dev/full; then
       env $i --help    >/dev/full 2>/dev/null && fail=1
       env $i --version >/dev/full 2>/dev/null && fail=1
@@ -97,7 +107,7 @@ for lang in C fr da; do
         : # ok
       else
         fail=1
-        echo "*** $i: bad exit status \`$status' (expected $expected)," 1>&2
+        echo "*** $i: bad exit status '$status' (expected $expected)," 1>&2
         echo "  with --help or --version output redirected to /dev/full" 1>&2
       fi
     fi
@@ -129,7 +139,7 @@ chown_setup () { args=--version; }
 mkfifo_setup () { args=--version; }
 mknod_setup () { args=--version; }
 # Punt on uptime, since it fails (e.g., failing to get boot time)
-# on some systems, and we shouldn't let that stop `make check'.
+# on some systems, and we shouldn't let that stop 'make check'.
 uptime_setup () { args=--version; }
 
 # Create a file in the current directory, not in $TMPDIR.
@@ -173,11 +183,21 @@ shred_setup () { args=$tmp_in; }
 touch_setup () { args=$tmp_in2; }
 truncate_setup () { args="--reference=$tmp_in $tmp_in2"; }
 
+mkid_setup () { printf 'f(){}\ntypedef int t;\n' > f.c; args=. ; }
+lid_setup () { args=; }
+fid_setup () { args=f.c; }
+fnid_setup () { args=; }
+xtokid_setup () { args=; }
+aid_setup () { args=f; }
+eid_setup () { args=--version; }
+gid_setup () { args=f; }
+defid_setup () { args=t; }
+
 basename_setup () { args=$tmp_in; }
 dirname_setup () { args=$tmp_in; }
 expr_setup () { args=foo; }
 
-# Punt, in case GNU `id' hasn't been installed yet.
+# Punt, in case GNU 'id' hasn't been installed yet.
 groups_setup () { args=--version; }
 
 pathchk_setup () { args=$tmp_in; }
